{{- if and .Values.backtestingWorker.enabled .Values.backtestingWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-backtesting-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-streamlit
  minReplicas: {{ .Values.backtestingWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backtestingWorker.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backtestingWorker.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
