apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-streamlit
  labels:
    app: {{ .Release.Name }}-streamlit
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.streamlit.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-streamlit

{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Release.Name }}-metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Release.Name }}-streamlit
{{- end }}
